package com.studentbag.backend.resources.dto.response;

import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;

@Getter
@Builder
public class PersonalResourceFolderResponse {

    private Long id;
    private Long ownerStudentId;
    private Long parentFolderId;
    private String name;
    private String path;
    private Long courseId;
    private Boolean isAutoGenerated;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}