spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_bag
    username: postgres
    password: ayman@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ayman.aljamal2017@gmail.com
    password: ihep rqnx jyyl ucnp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwt:
    secret: your_super_secret_key_123456789012345678901234567890
    expiration: 86400000