package com.studentbag.backend.resources.service;

import com.studentbag.backend.common.exception.ResourceNotFoundException;
import com.studentbag.backend.resources.entity.PersonalResourceFolder;
import com.studentbag.backend.resources.entity.PersonalResourceItem;
import com.studentbag.backend.resources.repository.PersonalResourceFolderRepository;
import com.studentbag.backend.resources.repository.PersonalResourceItemRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class PersonalResourceService {

    private final PersonalResourceFolderRepository folderRepository;
    private final PersonalResourceItemRepository itemRepository;

    public PersonalResourceFolder createFolder(PersonalResourceFolder folder) {
        return folderRepository.save(folder);
    }

    public PersonalResourceFolder updateFolder(Long id, PersonalResourceFolder updatedFolder) {
        PersonalResourceFolder existing = getFolderById(id);

        existing.setOwnerStudent(updatedFolder.getOwnerStudent());
        existing.setParentFolder(updatedFolder.getParentFolder());
        existing.setName(updatedFolder.getName());
        existing.setPath(updatedFolder.getPath());
        existing.setCourse(updatedFolder.getCourse());
        existing.setIsAutoGenerated(updatedFolder.getIsAutoGenerated());

        return folderRepository.save(existing);
    }

    public PersonalResourceFolder getFolderById(Long id) {
        return folderRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Personal resource folder not found with id: " + id));
    }

    public List<PersonalResourceFolder> getStudentFolders(Long studentId) {
        return folderRepository.findByOwnerStudentId(studentId);
    }

    public List<PersonalResourceFolder> getRootFolders(Long studentId) {
        return folderRepository.findByOwnerStudentIdAndParentFolderIsNull(studentId);
    }

    public List<PersonalResourceFolder> getChildFolders(Long parentFolderId) {
        return folderRepository.findByParentFolderId(parentFolderId);
    }

    public List<PersonalResourceFolder> getFoldersByCourse(Long studentId, Long courseId) {
        return folderRepository.findByOwnerStudentIdAndCourseId(studentId, courseId);
    }

    public void deleteFolder(Long id) {
        PersonalResourceFolder folder = getFolderById(id);
        folderRepository.delete(folder);
    }

    public PersonalResourceItem createItem(PersonalResourceItem item) {
        return itemRepository.save(item);
    }

    public PersonalResourceItem updateItem(Long id, PersonalResourceItem updatedItem) {
        PersonalResourceItem existing = getItemById(id);

        existing.setOwnerStudent(updatedItem.getOwnerStudent());
        existing.setFolder(updatedItem.getFolder());
        existing.setTitle(updatedItem.getTitle());
        existing.setFormat(updatedItem.getFormat());
        existing.setIsExamPreparation(updatedItem.getIsExamPreparation());
        existing.setIsImportant(updatedItem.getIsImportant());
        existing.setLinkedAdminResource(updatedItem.getLinkedAdminResource());
        existing.setNote(updatedItem.getNote());
        existing.setFileUrl(updatedItem.getFileUrl());

        return itemRepository.save(existing);
    }

    public PersonalResourceItem getItemById(Long id) {
        return itemRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Personal resource item not found with id: " + id));
    }

    public List<PersonalResourceItem> getStudentItems(Long studentId) {
        return itemRepository.findByOwnerStudentId(studentId);
    }

    public List<PersonalResourceItem> getFolderItems(Long folderId) {
        return itemRepository.findByFolderId(folderId);
    }

    public List<PersonalResourceItem> getImportantItems(Long studentId) {
        return itemRepository.findByOwnerStudentIdAndIsImportantTrue(studentId);
    }

    public List<PersonalResourceItem> getExamPreparationItems(Long studentId) {
        return itemRepository.findByOwnerStudentIdAndIsExamPreparationTrue(studentId);
    }

    public List<PersonalResourceItem> getItemsLinkedToAdminResource(Long adminResourceId) {
        return itemRepository.findByLinkedAdminResourceId(adminResourceId);
    }

    public List<PersonalResourceItem> getItemsLinkedToNote(Long noteId) {
        return itemRepository.findByNoteId(noteId);
    }

    public List<PersonalResourceItem> searchByTitle(Long studentId, String title) {
        return itemRepository.findByOwnerStudentIdAndTitleContainingIgnoreCase(studentId, title);
    }

    public PersonalResourceItem markImportant(Long itemId) {
        PersonalResourceItem item = getItemById(itemId);
        item.markImportant();
        return itemRepository.save(item);
    }

    public PersonalResourceItem moveToFolder(Long itemId, Long folderId) {
        PersonalResourceItem item = getItemById(itemId);
        PersonalResourceFolder folder = getFolderById(folderId);

        item.moveToFolder(folder);
        return itemRepository.save(item);
    }

    public void deleteItem(Long id) {
        PersonalResourceItem item = getItemById(id);
        itemRepository.delete(item);
    }
}