package com.studentbag.backend.resources.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PersonalResourceFolderRequest {

    @NotNull
    private Long ownerStudentId;

    private Long parentFolderId;

    @NotBlank
    private String name;

    @NotBlank
    private String path;

    private Long courseId;

    private Boolean isAutoGenerated = false;
}